KS-4-4. GYM
KharinAA1986/KotlinSprint pull request #19
Opened 2024-06-15 20:26 UTC by KharinAA1986

2024-06-15 21:58 UTC, ievetrovdev requested changes

2024-06-15 21:58 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/l4_task4.kt
> +                "Упражнения для пресса:\t ${(dayNumber % 2 == 0) == dayPressIsEven}"
Все верно, но ты постоянно дублируешь одно и тоже условие - это нарушение принципа DRY. Давай вынесем в отдельную переменную, что бы уменьшить кол-во повторяющейся логики.

2024-06-18 19:07 UTC, ievetrovdev requested changes

2024-06-18 19:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/l4_task4.kt
> +    val dayNumberIsEven = dayNumber % 2 == 0
Тут можно обойтись всего одной переменной

2024-06-19 17:45 UTC, KharinAA1986 commented on src/main/kotlin/lesson_4/l4_task4.kt
> +    val dayNumberIsEven = dayNumber % 2 == 0
Исправил, но теперь код стал менее понятным, менее гибким. Допустим, тренер поменяет ему план так, что упражнения для рук будут делаться каждый день и тогда придется внимательно перечитывать ТЗ, разбираться с инверсией где-то внутри функции

2024-06-19 19:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/l4_task4.kt
> +    val dayNumberIsEven = dayNumber % 2 == 0
Да, но старайся в целом стремиться к простым решениям. На реальном проекте подход согласовывается, и молодец, что замечаешь это уже тут.

2024-06-19 19:41 UTC, ievetrovdev approved these changes
Все верно!

2024-06-20 02:57 UTC, merged