KS-4-5. Ship* + readln (without checking input)
KharinAA1986/KotlinSprint pull request #20
Opened 2024-06-16 18:38 UTC by KharinAA1986

2024-06-16 21:22 UTC, ievetrovdev requested changes

2024-06-16 21:22 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/l4_task5.kt
Все верно, но давай разделим пустой строкой блоки задачи входных параметров, расчеты, вывод на экран результатов

2024-06-18 15:07 UTC, KharinAA1986 commented on src/main/kotlin/lesson_4/l4_task5.kt
Привет! Подскажи, пожалуйста: если я в комментарии к коммиту допустил ошибку (как здесь, например) или вовсе оставил его пустым, в IJ прожал Commit и перед нажатием Push  заметил эту ошибку, то как ее исправить?

2024-06-18 19:12 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/l4_task5.kt
git reset --soft HEAD^

в IntelliJ это так:

VCS > Git > Reset HEAD
Меняешь тип "Soft"
Меняешь commit на HEAD^

2024-06-18 19:12 UTC, ievetrovdev approved these changes
Все верно!

2024-06-19 14:12 UTC, merged